### ISSUE TITLE
#error This library needs at least a C++11 compliant compiler

### ISSUE THREAD

**Issue by soslug** [kvsjxd/VLC-Builder-for-Pi#1]
Hi I have been going around in circles with this problem and getting nowhere fast. 

I am using the latest raspbian jessie lite available and downloaded from raspberrypi.org latest release which have also been again updated via rpi-update and apt update & apt upgrade.

checking for egrep... (cached) /bin/grep -E
checking whether make sets $(MAKE)... (cached) yes
checking dependency style of gcc -std=gnu99... gcc3
checking for desktop-file-validate... desktop-file-validate
checking for c11-gcc... no
checking for c11... no
checking for c99-gcc... c99-gcc
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for C/C++ restrict keyword... __restrict
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... no
checking whether g++ supports C++11 features with -std=c++0x... no
configure: error: *** A compiler with support for C++11 language features is required.

Can you please advise on what further I need to add to your script to get it to run, if i was not a noob I could sought this out myself which I have tried to do, but a little help would go a long way.

**Comment by kvsjxd** [comment]
Try upgrading your gcc complier, if no updates are available try downloading latest gcc from debian sid repository for your architecture
